name: results-analyzer
channels:
  - pytorch
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py36h7b6447c_1
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - blosc=1.20.0=hd408876_0
  - brotlipy=0.7.0=py36h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py36_0
  - cffi=1.14.2=py36he30daa8_0
  - chardet=3.0.4=py36_1003
  - cryptography=3.0=py36h1ba5d50_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cudnn=7.6.5=cuda10.2_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.65.0=h3eb4bd4_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=hf484d3e_1000
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py36_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.2=py36_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py36_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.2.0=py36hdb11119_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - lzo=2.10=h7b6447c_2
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.3.1=1
  - matplotlib-base=3.3.1=py36h5ffbc53_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - mock=4.0.2=py_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.0=py36hfd86e86_0
  - notebook=6.1.3=py36h9f0ad1d_0
  - numexpr=2.7.1=py36h423224d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.4=py_0
  - pandas=1.1.1=py36h831f99a_0
  - pandoc=2.10.1=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.2=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=20.2.2=py36_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.6=py_0
  - prompt_toolkit=3.0.6=0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.20=py_2
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36hcca6a23_4
  - pyrsistent=0.16.0=py36h7b6447c_0
  - pysocks=1.7.1=py36_0
  - pytables=3.6.1=py36h71ec239_0
  - python=3.6.10=h7579374_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.6.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py36h7b6447c_1
  - pyzmq=19.0.1=py36he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.6=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py36_0
  - setuptools=49.6.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.0=py36h8c4c3a4_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py36_cu102
  - tornado=6.0.4=py36h7b6447c_1
  - traitlets=4.3.3=py36_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py36h9f0ad1d_1
  - wordcloud=1.8.0=py36h8c4c3a4_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.10.0
    - astunparse==1.6.3
    - attrs==20.3.0
    - beautifulsoup4==4.9.3
    - boto3==1.14.51
    - botocore==1.17.51
    - cachetools==4.1.1
    - click==7.1.2
    - commoncode==20.10.20
    - docutils==0.15.2
    - ernie==0.0.31b0
    - filelock==3.0.12
    - gast==0.3.3
    - google-auth==1.21.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - iniconfig==1.1.1
    - intbitset==2.4.1
    - jmespath==0.10.0
    - joblib==0.16.0
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pluggy==0.13.1
    - plugincode==20.9
    - protobuf==3.13.0
    - psycopg2==2.8.6
    - py==1.9.0
    - py-cpuinfo==5.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytest==6.1.2
    - regex==2020.7.14
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - saneyaml==0.4
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - sentencepiece==0.1.91
    - soupsieve==2.0.1
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - threadpoolctl==2.1.0
    - tokenizers==0.0.11
    - tqdm==4.48.2
    - transformers==2.4.1
    - typing==3.6.6
    - werkzeug==1.0.1
prefix: /home/ayan/anaconda3/envs/results-analyzer
