name: CI Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 4
      matrix:
        # Python 3.9 not supported until next scancode-toolkit version
        python-version: [3.6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Give permission to run scripts
        run: chmod +x ./docs/scripts/doc8_style_check.sh

      - name: Install Dependencies
        run:  cd docs && pip install -r requirements.txt	

      - name: Check Sphinx Documentation build minimally
        run: sphinx-build -E ./source ./build

      - name: Check for documentation style errors
        run: ./scripts/doc8_style_check.sh

